const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const ts = require('typescript');
const exportsObject = {};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/workFocus.ts','utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:exportsObject});
const select = exportsObject.selectWorkFocus;
const task = {id:'1',kind:'Tarea',title:'Revisar inventario',start:'09:00',end:'10:00',status:'Pendiente'};
const next = {...task,id:'2',start:'11:00',end:'12:00'};
assert.equal(select([task,next],'09:30').current.id,'1');
assert.equal(select([task,next],'09:30').next.id,'2');
assert.equal(select([{...task,status:'Completada'},next],'09:30').current,undefined);
assert.equal(select([{...task,completedAt:'2026-09-10'},next],'09:30').current,undefined);
assert.equal(select([{...task,status:'Pausada'},next],'09:30').current,undefined);
assert.equal(select([{...task,blocked:true},next],'09:30').current,undefined);
assert.equal(select([task,next],'10:30').label,'Pendiente de terminar');
assert.equal(select([task,next],'08:00',{start:'09:00',end:'18:00'}).label,'Fuera de turno');
assert.equal(select([{...task,startedAt:'2026-09-10'},next],'11:30').current.id,'1');
assert.equal(select([],'12:00').current,undefined);
assert.equal(select([task],'20:00',{start:'09:00',end:'18:00'}).current,undefined);
console.log('PASS: horario actual, siguiente, completadas, pausadas, autorización, retrasos, turno y actividad en curso');
assert.equal(exportsObject.workTimeAt(new Date('2026-09-10T19:30:00Z')), '13:30');
